// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['api']['App']['CheckForUpdate']();
}

export function GetAllTagNames() {
  return window['go']['api']['App']['GetAllTagNames']();
}

export function GetConfig() {
  return window['go']['api']['App']['GetConfig']();
}

export function GetLocaleMessages() {
  return window['go']['api']['App']['GetLocaleMessages']();
}

export function GetLogEntries(arg1) {
  return window['go']['api']['App']['GetLogEntries'](arg1);
}

export function GetLogList() {
  return window['go']['api']['App']['GetLogList']();
}

export function GetLogThreads(arg1) {
  return window['go']['api']['App']['GetLogThreads'](arg1);
}

export function GetSetupState() {
  return window['go']['api']['App']['GetSetupState']();
}

export function GetTags(arg1) {
  return window['go']['api']['App']['GetTags'](arg1);
}

export function GetVersion() {
  return window['go']['api']['App']['GetVersion']();
}

export function PickDirectory() {
  return window['go']['api']['App']['PickDirectory']();
}

export function SaveConfig(arg1) {
  return window['go']['api']['App']['SaveConfig'](arg1);
}

export function ScanLogs() {
  return window['go']['api']['App']['ScanLogs']();
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['Search'](arg1, arg2, arg3, arg4);
}

export function SetTags(arg1, arg2, arg3) {
  return window['go']['api']['App']['SetTags'](arg1, arg2, arg3);
}
