// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {config} from '../models';
import {tags} from '../models';

export function CheckForUpdate():Promise<api.UpdateCheckResult>;

export function DetectedLogDirs():Promise<Array<string>>;

export function DownloadAndApplyUpdate():Promise<void>;

export function GetAllTagNames():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetLocaleMessages():Promise<Record<string, string>>;

export function GetLogEntries(arg1:string):Promise<Array<api.EntryDTO>>;

export function GetLogList():Promise<Array<api.LogSummary>>;

export function GetLogThreads(arg1:string):Promise<Array<api.ThreadDTO>>;

export function GetSetupState():Promise<api.SetupState>;

export function GetTags(arg1:string):Promise<tags.FileTags>;

export function GetVersion():Promise<string>;

export function PickDirectory():Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanLogs():Promise<Array<api.LogSummary>>;

export function Search(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<api.SearchResponse>;

export function SetTags(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;
